// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ucore_web_ASPNET {
	
	
	public partial class UCompiler {
		
		protected System.Web.UI.HtmlControls.HtmlForm form_l;
		
		protected System.Web.UI.WebControls.Button asp_btl;
		
		protected System.Web.UI.HtmlControls.HtmlForm form_r;
		
		protected System.Web.UI.WebControls.Button asp_btr;
		
		protected System.Web.UI.WebControls.Button asp_ctr;
	}
}
